### ISSUE TITLE
release tagging problem

### ISSUE THREAD

**Issue by wenboown** [SeineAI/SeineSailor#14]
We added 
https://github.com/SeineAI/SeineSailor/blob/5bbf1d04d3320735da04a94b61c1dc865508b968/.github/workflows/release.yml#L42

to `release-drafter`. It correctly tagged one release as `latest`. But afterwards it cannot create any new releases. 

https://github.com/SeineAI/SeineSailor/actions/runs/9104260759/job/25027772624#step:2:229
```
SeineAI/SeineSailor: Creating new release
{ name: 'event', id: '9104260759' }
Error: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}
```

**Comment by wenboown** [comment]
I want to separate production (stable) and development (latest). can you help me?

Currently, I have a workflow file that refers:
      - name: Run SeineSailor
        uses: SeineAI/SeineSailor@latest

which points to the latest tag release we made above.

then the action.yml has:
  using: 'docker'
  image: 'docker://ghcr.io/seineai/seine_sailor:latest' # change the latest to v1, v2... to separate dev and release

Which points to a docker image that we build and push when creating the latest release.

But I think the ideal setup should be:
when I make a push or manually trigger a build workflow. it updates the latest docker image for the development. so an action.yml points to the "latest" or "dev" docker image.
when I am ready for a release. It creates a new release and updates a docker image with "stable" or "prod" tag, and have the action.yml points to it. 
Then I can instruct my users to use a workflow yml points to uses: SeineAI/SeineSailor@stable
and my development team use a workflow yml points to uses: SeineAI/SeineSailor@latest

is this possible?

**Comment by wenboown** [comment]
ChatGPT-4o said:

Yes, it is possible to set up separate workflows for development (latest) and production (stable) Docker images, and to have your GitHub Actions workflows use the appropriate version for each environment. Below is a detailed plan on how to achieve this.

### 1. Update Development Docker Image

Create a workflow that builds and pushes the Docker image with the `latest` tag whenever there's a push to the `main` branch or a manual trigger.

#### Workflow: `.github/workflows/update-latest.yml`

```yaml
name: Update Latest Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/seineai/seine_sailor:latest .
          docker push ghcr.io/seineai/seine_sailor:latest
```

### 2. Create Stable Release and Update Production Docker Image

Create a workflow that builds and pushes the Docker image with a versioned tag and updates the `stable` tag. This workflow will be triggered manually when you're ready to release.

#### Workflow: `.github/workflows/update-stable.yml`

```yaml
name: Update Stable Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push versioned Docker image
        run: |
          VERSION=$(date +%Y%m%d%H%M%S) # or use any versioning scheme you prefer
          docker build -t ghcr.io/seineai/seine_sailor:$VERSION .
          docker push ghcr.io/seineai/seine_sailor:$VERSION

      - name: Update stable tag
        run: |
          docker tag ghcr.io/seineai/seine_sailor:$VERSION ghcr.io/seineai/seine_sailor:stable
          docker push ghcr.io/seineai/seine_sailor:stable
```

### 3. Modify `action.yml` to Use Appropriate Docker Tags

Update your `action.yml` to point to either `latest` or `stable` based on the intended usage.

#### `action.yml`

```yaml
name: 'SeineSailor'
description: 'Your action description'
author: 'SeineAI'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/seineai/seine_sailor:${{ inputs.tag }}'

inputs:
  tag:
    description: 'Tag of the Docker image to use'
    required: true
    default: 'stable' # or 'latest' for development
```

### 4. Using the Action in Workflows

#### For Development Team

```yaml
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use SeineSailor Latest
        uses: SeineAI/SeineSailor@latest
        with:
          tag: latest
```

#### For Production

```yaml
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use SeineSailor Stable
        uses: SeineAI/SeineSailor@stable
        with:
          tag: stable
```

### Summary

1. **Development Workflow**: Updates the `latest` Docker image on push to `main` or manual trigger.
2. **Release Workflow**: Manually triggered to create a versioned Docker image and update the `stable` tag.
3. **Action Configuration**: `action.yml` uses an input to select between `latest` and `stable` Docker images.
4. **Workflow Usage**: Separate workflows for development (`latest`) and production (`stable`). 

This setup ensures a clear separation between development and production environments and allows for easy updates and deployment.
